### ISSUE TITLE
Testing ultimate checklist

### ISSUE THREAD

**Issue by iker-gonzalez** [iker-gonzalez/webserv#17]
**Check the code and ask questions**
- [x]  Launch the installation of siege with homebrew. @iker-gonzalez 
- [x]  Ask explanations about the basics of an HTTP server. @iker-gonzalez 
- [x]  Ask what function the group used for I/O Multiplexing. @zcanales 
- [x]  Ask for an explanation of how does select() (or equivalent) work. @zcanales 
- [x]  Ask if they use only one select() (or equivalent) and how they've managed the server to accept and the client to read/write. @zcanales 
- [x]  The select() (or equivalent) should be in the main loop and should check file descriptors for read and write AT THE SAME TIME. If not, the grade is 0 and the evaluation process ends now. @zcanales 
- [x]  There should be only one read or one write per client per select() (or equivalent). Ask the group to show you the code from the select() (or equivalent) to the read and write of a client. @zcanales 
- [x]  Search for all read/recv/write/send on a socket and check that, if an error is returned, the client is removed. @zcanales 
- [x]  Search for all read/recv/write/send and check if the returned value is correctly checked (checking only -1 or 0 values is not enough, both should be checked). @zcanales 
- [x]  If errno is checked after read/recv/write/send, the grade is 0 and the evaluation process ends now. -> eliminate all references to errno. Currently are some of them.
- [x]  Writing or reading ANY file descriptor without going through the select() (or equivalent) is strictly FORBIDDEN. @zcanales 
- [x]  The project must compile without any re-link issue. If not, use the 'Invalid compilation' flag. @iker-gonzalez 
- [x]  If any point is unclear or is not correct, use the flag for 'Incomplete work'.

**Configuration:**

- [x]  In the configuration file, check whether you can do the following and test the result:
- [x]  Search for the HTTP response status codes list on the internet. During this evaluation, if any status codes is wrong, don't give any related points. @iker-gonzalez 
- [x]  Setup multiple servers with different ports. @iker-gonzalez 
- [x]  Setup multiple servers with different hostnames (use something like: curl --resolve example.com:80:127.0.0.1 http://example.com/). @iker-gonzalez 
- [x]  Setup default error page (try to change the error 404). @iker-gonzalez 
- [x]  Limit the client body (use: curl -X POST -H "Content-Type: plain/text" --data "BODY IS HERE write something shorter or longer than body limit"). @iker-gonzalez 
- [x]  Setup routes in a server to different directories. @iker-gonzalez 
- [x]  Setup a default file to search for if you ask for a directory. @iker-gonzalez 
- [x]  Setup a list of methods accepted for a certain route (e.g., try to delete something with and without permission). @iker-gonzalez 

**Basic checks:**

- [x]  Using telnet, curl, prepared files, demonstrate that the following features work properly:
- [x]  GET requests -> should work
- [x]  POST requests -> should work
- [x]  DELETE requests -> should work
- [x]  UNKNOWN requests -> should not produce any crash
- [x]  For every test the status code must be correct @iker-gonzalez 
- [x]  Upload some file to the server and get it back

**Check CGI:** @zcanales 

- [x]  The server is working fine using a CGI.
- [x]  The CGI should be run in the correct directory for relative path file access.
- [x]  With the help of the evaluation group you should check that everything is working properly. You have to test the CGI with the methods "GET", "POST" and "DELETE".
- [x]  You need to test with files containing errors to see if the error handling works properly. 
- [x] You need to test with files containing errors to see if the error handling works properly. You can use a script containing an infinite loop or an error; you are free to do whatever tests you want within the limits of acceptability that remain at your discretion. The group being evaluated should help you with this.
- [x] The server should never crash and an error should be visible in case of a problem.

**Check with a browser**

- [x] Use the reference browser of the team. Open the network part of it, and try to connect to the server using it. @iker-gonzalez 
- [x] Look at the request header and response header. @iker-gonzalez 
- [x] It should be compatible to serve a fully static website. @iker-gonzalez 
- [x] Try a wrong URL on the server. @iker-gonzalez 
- [x] Try to list a directory. -> **when requesting a directory it should show a directory. Currently going to 404.**
- [x] Try a redirected URL. @iker-gonzalez 
- [x] Try anything you want to. @iker-gonzalez 

**Port issues**
- [x] In the configuration file setup multiple ports and use different websites. Use the browser to ensure that the configuration works as expected and shows the right website. @iker-gonzalez 
- [x] In the configuration, try to setup the same port multiple times. It should not work. @iker-gonzalez 
- [x] Launch multiple servers at the same time with different configurations but with common ports. Does it work? If it does, ask why the server should work if one of the configurations isn't functional. Keep going. @iker-gonzalez 

**Siege & stress test**
- [x] Use Siege to run some stress tests. @iker-gonzalez 
- [x] Availability should be above 99.5% for a simple GET on an empty page with a siege -b on that page. @iker-gonzalez 
- [x] Verify there is no memory leak (Monitor the process memory usage. It should not go up indefinitely). @iker-gonzalez 
- [x] Check if there is no hanging connection. @iker-gonzalez 
- [x] You should be able to use siege indefinitely without having to restart the server (take a look at siege -b). @iker-gonzalez
